### ISSUE TITLE
Checking if the is acquisition complete is incorrect in sc_buffer.py

### ISSUE THREAD

**Issue by Ryan-McClanahan** [slaclab/edef#1]
The current docstring reads

    def is_acquisition_complete(self):
        """Checks if the buffer is done collecting data.
        Looks to see if the "Total Acquired so far" PV matches the "Total to Acquire" PV.
        If the two match, it is assumed that data acquisition is complete.
        Raises an exception if the buffer was not properly reserved.
        Returns:
            bool: True if acquisition is complete, False otherwise.
        """

acquisition is not complete at this point because the point where BSA:SYS0:1:{21:49}:MEASCNT ==  BSA:SYS0:1:{21:49}:CNT is not necessarily when the data is transferred to EPICS.

When BSA:SYS0:{21:49}:HST_READY == 1 is when the data has been transferred to EPICS.

**Comment by mattgibbs** [comment]
Thanks @Ryan-McClanahan!  The perils of assuming what worked for NC works for SC.  I'll get this fixed soon...

**Comment by Ryan-McClanahan** [comment]
@mattgibbs awesome, Thanks!

**Comment by mattgibbs** [comment]
Fixed in #5
